name: community_board_frontend
description: Flutter client for the community board service with CKEditor 5 integration
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.2.0
  http: ^1.2.1
  intl: ^0.19.0
  flutter_inappwebview: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/editor/
