version: '3.9'

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: community_board
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      retries: 5
    networks:
      - internal

  backend:
    build: ./backend
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=community_board
      - DATABASE_USER=root
      - DATABASE_PASSWORD=changeme
      - JWT_SECRET=super-secret-key
      - PORT=4000
      - APP_URL=https://community-board.localhost
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - traefik

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - traefik

  traefik:
    image: traefik:v3.1
    command:
      - '--providers.file.directory=/etc/traefik/dynamic'
      - '--entryPoints.web.address=:80'
      - '--entryPoints.websecure.address=:443'
      - '--certificatesresolvers.lets-encrypt.acme.tlschallenge=true'
      - '--certificatesresolvers.lets-encrypt.acme.email=admin@example.com'
      - '--certificatesresolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./traefik/dynamic_config.yml:/etc/traefik/dynamic/dynamic_config.yml:ro
      - traefik_certs:/letsencrypt
    networks:
      - traefik

volumes:
  db_data:
  traefik_certs:

networks:
  internal:
  traefik:
